services:
  - type: web
    name: codex-online
    env: static
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildCommand: npm install && npm run build
